/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.luthfipun.kotlinffmpeg


fun main() {

    val fileURL = "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_30MB.mp4"
    val outputName = System.currentTimeMillis().toString()

    val videoCropping = VideoCropping.Builder()
        .setFileName(fileUrl = fileURL)
        .setOutputName(outputName = outputName)
        .build()

    videoCropping.startCrop(object : VideoCroppingListener {
        override fun onComplete() {
            println("Crop completed!")
        }

        override fun onError(e: Exception) {
            println("Crop error : ${e.message}")
        }
    })
}