/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.luthfipun.kotlinffmpeg

import java.nio.file.Paths

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val path = Paths.get("").toAbsolutePath().toString()
    println(path)
}
